-- Database: GLOBALASW Metadata version: 2 Exported: Aug 16, 2019
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_PULL_TEST" USING 'GCG_PULL_TEST000.mkd' PAGESIZE=4096 (
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "SERIAL" CHAR(50),
 "SCREEN_ID" CHAR(50),
 "TEST_NO" NUMERIC(8,2),
 "FRONT" NUMERIC(8,2),
 "BACK" NUMERIC(8,2),
 "EMPL_LAST_CHANGE" CHAR(20),
 "DATE_LAST_CHANGE" DATE,
 "FRONT_AVG" CHAR(20),
 "BACK_AVG" CHAR(20),
 "SEQ" CHAR(6) );
-- End Multi-Line Statement
CREATE INDEX "PullTestK00" USING 0  ON "GCG_PULL_TEST" ( "JOB", "SUFFIX" );
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
