-- Database: GLOBALASW Metadata version: 2 Exported: Aug 16, 2019
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_SCREEN_LIQ_DYE" USING 'GCG_SCREEN_LIQ_DYE000.mkd' PAGESIZE=4096 (
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "SERIAL" CHAR(50),
 "CLEANER_TYPE" CHAR(20),
 "PENETRANT_TYPE" CHAR(20),
 "DEVELOPER_TYPE" CHAR(20),
 "SURFACE_TEMP" CHAR(20),
 "PRE_CLEAN_DRY" CHAR(20),
 "PENETRANT_DRY" CHAR(20),
 "POST_REMOVAL_DRY" CHAR(20),
 "DEVELOPER_DRY" CHAR(20),
 "WELD_1" CHAR(4),
 "WELD_2" CHAR(4),
 "WELD_3" CHAR(4),
 "WELD_4" CHAR(4),
 "WELD_5" CHAR(4),
 "WELD_6" CHAR(4),
 "WELD_7" CHAR(4),
 "WELD_8" CHAR(4),
 "WELD_9" CHAR(4),
 "WELD_10" CHAR(4),
 "WELD_11" CHAR(4),
 "WELD_12" CHAR(4),
 "EMPL_LAST_CHANGE" CHAR(20),
 "DATE_LAST_CHANGE" DATE,
 "SEQ" CHAR(6) );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
