-- Database: GLOBALASW Metadata version: 2 Exported: Aug 16, 2019
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_ACPT_RJCT" USING 'GCG_ACPT_RJCT.mkd' PAGESIZE=4096 (
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "SERIAL" CHAR(50),
 "SCREEN_ID" CHAR(50),
 "LOG_SHEET" CHAR(15),
 "EMPL_LAST_CHANGE" CHAR(20),
 "DATE_LAST_CHANGE" DATE,
 "ACCEPTED" CHAR(7),
 "TIME" CHAR(50),
 "SEQ" CHAR(6) );
-- End Multi-Line Statement
CREATE INDEX "ActpRjctK00" USING 0  ON "GCG_ACPT_RJCT" ( "JOB", "SUFFIX" );
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
