-- Database: GLOBALASW Metadata version: 2 Exported: Aug 16, 2019
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_WELD_SCREEN" USING 'GCG_WELD_SCREEN.mkd' PAGESIZE=4096 (
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "SERIAL" CHAR(50),
 "POINT_ID" CHAR(3),
 "COMP_LOT" CHAR(30),
 "COMP_HEAT" CHAR(30),
 "COMP_SERIAL" CHAR(30),
 "WW_LOT" CHAR(30),
 "WW_HEAT" CHAR(30),
 "WW_SERIAL" CHAR(30),
 "WELD_WIRE" CHAR(30),
 "SCREEN_ID" CHAR(50),
 "EMPL_LAST_CHANGE" CHAR(20),
 "DATE_LAST_CHANGE" DATE,
 "REC_ID" INTEGER,
 "Flag_Sand_Check" BIT NOT NULL,
 "SEQ" CHAR(6) );
-- End Multi-Line Statement
CREATE INDEX "WeldScreenK00" USING 0  ON "GCG_WELD_SCREEN" ( "JOB", "SUFFIX" );
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
