-- Database: GLOBALASW Metadata version: 2 Exported: Aug 16, 2019
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_HEAT_CHECK_TEMP" USING 'GCG_HEAT_CHECK_TEMP.mkd' PAGESIZE=4096 (
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "BATCH" CHAR(15),
 "TEMP" NUMERIC(8,2),
 "EMPL_LAST_CHANGE" CHAR(20),
 "DATE_LAST_CHANGE" DATE,
 "ACCEPTED" CHAR(7),
 "TIME" CHAR(15),
 "SCREEN_ID" CHAR(50),
 "COMP_ID" INTEGER,
 "SERIAL" CHAR(50),
 "SEQ" CHAR(6) );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
